# Generated by Django 2.1.5 on 2019-02-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='defautlt comm'),
            preserve_default=False,
        ),
    ]
