# Generated by Django 2.1.7 on 2019-02-24 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190224_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_limit',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
