# Generated by Django 2.1.7 on 2019-02-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190224_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmembers',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='blog.Post'),
        ),
    ]
